gcs backends

diff --git a/bin/archive b/bin/archive
--- a/bin/archive
+++ b/bin/archive
@@ -33,51 +33,45 @@ check_args() {
   fi
 }
 
-spaces_cmd() {
-  local cmd=$*
-  s3cmd \
-    --access_key="${TF_VAR_aws_access_key_id}" \
-    --secret_key="${TF_VAR_aws_secret_access_key}" \
-    --host="${TF_VAR_region}.digitaloceanspaces.com" \
-    --host-bucket="%(bucket)s.${TF_VAR_region}.digitaloceanspaces.com" \
-    ${cmd}
-}
-
 check_ansible_archive() {
-  local key=$1
-  spaces_cmd ls s3://${state_bucket}/${key} | grep -qs ansible
+  local object_url=$1
+  gsutil ls ${object_url} | grep -qs ansible
 }
 
 remove_ansible_archive() {
   local key=$1
-  spaces_cmd rm s3://${state_bucket}/${key} \
-    || die "unable to remove ansible archive s3://${state_bucket}/${key}"
+  gsutil rm ${object_url} \
+    || die "unable to remove ansible archive ${object_url}"
 }
 
 publish_ansible_archive() {
   local tarball_path=$1
   local key=$2
-  spaces_cmd put $tarball_path s3://${state_bucket}/${key} \
-    || die "Unable to publish ansible archive to s3://${state_bucket}/${key}"
+  gsutil cp $tarball_path ${object_url} \
+    || die "Unable to publish ansible archive to ${object_url}"
 }
 
 create_ansible_archive() {
   local tarball_path=$1
-  cd ${project_dir}/provision
+  local project_dir=$(git rev-parse --show-toplevel)
+  cd ${project_dir}/terraform/provision
   tar czf $tarball_path --exclude=tmp ansible
 }
 
 archive_ansible() {
+  local proto="gs"
+  local state_bucket="${TF_VAR_stack_state_bucket}"
   local key="infrastructure/${project}/${environment}/ansible/ansible.tar.gz"
+  local object_url="${proto}://${state_bucket}/${key}"
 
   if [ -n "$update_archive" ]; then
-    remove_ansible_archive $key
+    remove_ansible_archive $object_url
   fi
 
-  if ! check_ansible_archive $key; then
+  if ! check_ansible_archive $object_url; then
     local tempfile=$(mktemp -p"/tmp" ansible-XXXXXX.tar.gz)
     create_ansible_archive $tempfile
-    publish_ansible_archive $tempfile $key
+    publish_ansible_archive $tempfile $object_url
     rm -f $tempfile
   fi
 }
@@ -99,12 +93,6 @@ main() {
   shift $(($OPTIND - 1))
   action=$1
   check_args
-
-  region="${TF_VAR_region:-ams3}"
-  state_bucket="${TF_VAR_stack_state_bucket}" #"do-stacks-ams3"
-
-  project_dir=$(git rev-parse --show-toplevel)
-
 
   case $action in
     *)
